name: Build and Deploy Script
<<<<<<< Updated upstream:.github/workflows/main.yml
concurrency:
  group: github-pages
  cancel-in-progress: true
=======
>>>>>>> Stashed changes:.github/workflows/gh-pages.yml
on:
  push:
    branches:
      - gh-pages
jobs:
  build:
    runs-on: ubuntu-latest
<<<<<<< Updated upstream:.github/workflows/main.yml
    environment: github-pages
=======
>>>>>>> Stashed changes:.github/workflows/gh-pages.yml
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Adding Node.js
      uses: actions/setup-node@v2
      with:
          node-version: 18
    
    - name: Install Dependencies
      run: npm install
    
    - name: Build
      run: npm run build:prod

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/angular-github-actions
        enable_jekyll: true

    
    

      
      
