name: Build and Deploy Script
concurrency:
  group: github-pages
  cancel-in-progress: true
on:
  push:
    branches:
      - gh-pages
jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Adding Node.js
      uses: actions/setup-node@v2
      with:
          node-version: 18
    
    - name: Install Dependencies
      run: npm install

    - name: Deploy to gh pages
      run: |
        npm run build-and-deploy-gh-pages
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_Token }}

    
    

      
      
